accounts:
  - name: alice
    coins: ["200000000umedas"]
  - name: bob
    coins: ["100000000umedas"]
validator:
  name: alice
  staked: "100000000umedas"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000umedas"]
