version: 1
build:
  ldflags:
  - -X main.Env=prod
  - -X main.Version=1.0.0
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: Medas
  coins:
  - 100000000000000umedas
- name: Eike
  coins:
  - 50000000000000umedas
- name: Erik
  coins:
  - 5000000000000umedas
- name: Julia
  coins:
  - 5000000000000umedas
- name: Hans
  coins:
  - 5000000000000umedas
- name: Ilse
  coins:
  - 5000000000000umedas
faucet:
  name: Erik
  coins:
  - 100000umedas
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    mint:
      minter:
        inflation: "0.250000000000000000"
      params:
        blocks_per_year: "5256000"
        goal_bonded: "0.670000000000000000"
        inflation_max: "0.250000000000000000"
        inflation_min: "0.050000000000000000"
        inflation_rate_change: "0.240000000000000000"
        mint_denom: umedas
    staking:
      params:
        bond_denom: umedas
  chain_id: medasdigital-1
validators:
- name: Eike
  bonded: 40000000000000umedas
