accounts:
  - name: Erik
    coins: ["2000000000umedas"]
  - name: Julia
    coins: ["1000000000umedas"]
  - name: Eike
    coins: ["1000000000umedas"]
  - name: Neptun 
    coins: ["1000000000umedas"]
  - name: Hans
    coins: ["1000000000umedas"]
  - name: Ilse
    coins: ["1000000000umedas"]

validator:
  name: Erik
  staked: "10000000umedas"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: Julia
  coins: ["100000umedas"]
genesis:
  chain_id: "medasdigital-test"
  app_state:
    staking:
      params:
        bond_denom: "umedas"
    mint:
      minter: 
        inflation: "0.530000000000000000" 
      params: 
        blocks_per_year: "5256000"
        goal_bonded: "0.670000000000000000"
        inflation_max: "0.530000000000000000"
        inflation_min: "0.410000000000000000"
        inflation_rate_change: "0.240000000000000000" 
        mint_denom: "umedas"    
